spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/shop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  profiles:
    include: oauth


logging-level:
  org.hibernate.SQL: debug

file:
  dir: C:\Users\USER\Backend\workspace\shop\src\main\resources\static\img\